sudo: false
language: python
python:
  - "3.7-dev"
  - "3.6"
  - "3.5"  
install:
  - pip install codecov
  - pip3 install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl
script:
  - cd dataflow
  - make tests  
after_success:
  - codecov
