sudo: false
language: python
python:
  - "3.6"
install:
  - pip install codecov
  - pip3 install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl
  - pip3 install matplotlib
  - pip3 install imageio
script:
  - cd dataflow
  - make tests  
after_success:
  - bash <(curl -s https://codecov.io/bash) -F unittests
